name: "Create github release entry"
runs:
    using: "composite"
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Create release
          shell: bash
          env:
              tag: ${{ github.ref_name }}
          run: ${{ github.action_path }}/scripts/make-release
